export const FETCH_RESOURCE_TREE = 'FETCH_RESOURCE_TREE';
export const SET_RESOURCE_TREE_NODE_LOADING = 'SET_RESOURCE_TREE_NODE_LOADING';
export const SAVE_RESOURCE_TREE = 'SAVE_RESOURCE_TREE';
export const SET_RESOURCE_OPEN_KEYS = 'SET_RESOURCE_OPEN_KEYS';
export const SET_RESOURCE_SEARCH_TEXT = 'SET_RESOURCE_SEARCH_TEXT';