export const COMMON_LAYOUT_TOGGLE_SIDEBAR = 'COMMON_LAYOUT_TOGGLE_SIDEBAR'
export const COMMON_LAYOUT_SHOW_SIDEBAR = 'COMMON_LAYOUT_SHOW_SIDEBAR'
export const COMMON_LAYOUT_HIDE_SIDEBAR = 'COMMON_LAYOUT_HIDE_SIDEBAR'
