// 切换 Header
export const COMMON_LAYOUT_TOGGLE_HEADER = 'COMMON_LAYOUT_TOGGLE_HEADER'
// 显示 Header
export const COMMON_LAYOUT_SHOW_HEADER = 'COMMON_LAYOUT_SHOW_HEADER'
// 影藏 Header
export const COMMON_LAYOUT_HIDE_HEADER = 'COMMON_LAYOUT_HIDE_HEADER'
// 切换 Header，滑动效果
export const COMMON_LAYOUT_TOGGLE_HEADER_SLIDE = 'COMMON_LAYOUT_TOGGLE_HEADER_SLIDE'
// 显示 Header，滑动效果
export const COMMON_LAYOUT_SHOW_HEADER_SLIDE = 'COMMON_LAYOUT_SHOW_HEADER_SLIDE'
// 影藏 Header，滑动效果
export const COMMON_LAYOUT_HIDE_HEADER_SLIDE = 'COMMON_LAYOUT_HIDE_HEADER_SLIDE'

// 切换 Sidebar
export const COMMON_LAYOUT_TOGGLE_SIDEBAR = 'COMMON_LAYOUT_TOGGLE_SIDEBAR'
// 显示 Sidebar
export const COMMON_LAYOUT_SHOW_SIDEBAR = 'COMMON_LAYOUT_SHOW_SIDEBAR'
// 影藏 Sidebar
export const COMMON_LAYOUT_HIDE_SIDEBAR = 'COMMON_LAYOUT_HIDE_SIDEBAR'
// 切换 Sidebar，滑动效果
export const COMMON_LAYOUT_TOGGLE_SIDEBAR_SLIDE = 'COMMON_LAYOUT_TOGGLE_SIDEBAR_SLIDE'
// 显示 Sidebar，滑动效果
export const COMMON_LAYOUT_SHOW_SIDEBAR_SLIDE = 'COMMON_LAYOUT_SHOW_SIDEBAR_SLIDE'
// 影藏 Sidebar，滑动效果
export const COMMON_LAYOUT_HIDE_SIDEBAR_SLIDE = 'COMMON_LAYOUT_HIDE_SIDEBAR_SLIDE'

// 切换 Sidebar 折叠
export const COMMON_LAYOUT_TOGGLE_SIDEBAR_COLLAPSE = 'COMMON_LAYOUT_TOGGLE_SIDEBAR_COLLAPSE'
// 展开 Sidebar 
export const COMMON_LAYOUT_EXPAND_SIDEBAR = 'COMMON_LAYOUT_EXPAND_SIDEBAR'
// 折叠 Sidebar
export const COMMON_LAYOUT_COLLAPSE_SIDEBAR = 'COMMON_LAYOUT_COLLAPSE_SIDEBAR'


// ------------------------------------

// 获取数据
export const GET_PRIVILEGE_MENU_TREE = 'GET_PRIVILEGE_MENU_TREE'
// 设置数据
export const SET_PRIVILEGE_MENU_TREE = 'SET_PRIVILEGE_MENU_TREE'
// 设置数据加载状态
export const SET_PRIVILEGE_MENU_TREE_LOADING = 'SET_PRIVILEGE_MENU_TREE_LOADING'


// 设置子路由
export const COMMON_LAYOUT_SET_SUB_ROUTES = 'COMMON_LAYOUT_SET_SUB_ROUTES'